#!/bin/bash
clear

for i in A B C
do
	cd /mnt/usb/RECORDER/FOLDER_$i
	case $i in
	A) cp -n * ~/Dropbox/ntnu/fthingel/mikro/forelesninger/audio
		;;
	B) cp -n * ~/Dropbox/ntnu/fthingel/anvendt/forelesninger/audio
		;;
	C) cp -n * ~/Dropbox/ntnu/fthingel/signal/forelesninger/audio
	esac
done
